# This workflow will run tests using node

name: Yarn Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn global add react@^16.14.0
      - run: yarn install --frozen-lockfile
        working-directory: react-highlight-within-textarea
      - run: yarn test
        working-directory: react-highlight-within-textarea

