# This workflow will run tests using node

name: Yarn Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: npm install -g nwb
      - run: yarn install
      - run: yarn install --dev
      - run: ls node_modules
      - run: yarn build
